// <auto-generated />
using System;
using Kenergie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kenergie.Migrations
{
    [DbContext(typeof(KenergieDbContext))]
    partial class KenergieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kenergie.Models.Agent", b =>
                {
                    b.Property<int>("IdAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseResidence")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAgent")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EtatCivil")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Fonction")
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Matricule")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomComplet")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelephoneAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("Zone")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdAgent");

                    b.HasIndex("EmailAgent")
                        .IsUnique()
                        .HasDatabaseName("IX_Agents_Email_Unique");

                    b.HasIndex("IdSociete");

                    b.HasIndex("Matricule")
                        .IsUnique()
                        .HasDatabaseName("IX_Agents_Matricule_Unique");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Agents_SerialNumber_Unique");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Kenergie.Models.ArriereeCrashed", b =>
                {
                    b.Property<int>("IdArriereeCrashed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Annees")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodeCons")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DateCorrection")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DonneesBrutesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErreursJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdClientFactureCree")
                        .HasColumnType("int");

                    b.Property<string>("MessageErreur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mois")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Montant")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumeroLigne")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeErreur")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdArriereeCrashed");

                    b.HasIndex("CodeCons")
                        .HasDatabaseName("IX_ArriereeCrashed_CodeCons");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_ArriereeCrashed_DateCreation");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdClientFactureCree");

                    b.HasIndex("Statut")
                        .HasDatabaseName("IX_ArriereeCrashed_Statut");

                    b.ToTable("ArriereesCrashed");
                });

            modelBuilder.Entity("Kenergie.Models.AuditLog", b =>
                {
                    b.Property<long>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAudit");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLog_Action");

                    b.HasIndex("DateAction")
                        .HasDatabaseName("IX_AuditLog_DateAction");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_AuditLog_IdSociete");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLog_UserId");

                    b.HasIndex("TableName", "RecordId")
                        .HasDatabaseName("IX_AuditLog_Table_Record");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Kenergie.Models.Axe", b =>
                {
                    b.Property<int>("IdAxe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeAxe")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdCabine")
                        .HasColumnType("int");

                    b.Property<string>("NomAxe")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("IdAxe");

                    b.HasIndex("IdCabine")
                        .HasDatabaseName("IX_Axe_IdCabine");

                    b.ToTable("Axes");
                });

            modelBuilder.Entity("Kenergie.Models.Cabine", b =>
                {
                    b.Property<int>("IdCabine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CodeCabine")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("IdCabine");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Cabine_IdSociete");

                    b.ToTable("Cabines");
                });

            modelBuilder.Entity("Kenergie.Models.CategorieClient", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("NomCategorie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdCategorie");

                    b.HasIndex("IdSociete");

                    b.HasIndex("NomCategorie", "IdSociete")
                        .HasDatabaseName("IX_CategorieClient_NomCategorie_IdSociete");

                    b.ToTable("CategorieClients");
                });

            modelBuilder.Entity("Kenergie.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseClient")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CodeCons")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailClient")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("GenreClient")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("IdAxe")
                        .HasColumnType("int");

                    b.Property<bool>("IsActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdClient");

                    b.HasIndex("CodeCons")
                        .IsUnique()
                        .HasDatabaseName("IX_Client_CodeCons_Unique");

                    b.HasIndex("IdAxe")
                        .HasDatabaseName("IX_Client_IdAxe");

                    b.HasIndex("UpdatedAt", "IdClient")
                        .HasDatabaseName("IX_Clients_Sync");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Kenergie.Models.ClientCrashed", b =>
                {
                    b.Property<int>("IdClientCrashed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseClient")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CodeCons")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DateCorrection")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DonneesBrutesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailClient")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ErreursJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreClient")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("IdClientCree")
                        .HasColumnType("int");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("LibelleUsage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageErreur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomClient")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumeroLigne")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeErreur")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdClientCrashed");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_ClientCrashed_DateCreation");

                    b.HasIndex("IdClientCree");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_ClientCrashed_IdSociete");

                    b.HasIndex("Statut")
                        .HasDatabaseName("IX_ClientCrashed_Statut");

                    b.ToTable("ClientsCrashed");
                });

            modelBuilder.Entity("Kenergie.Models.ClientFacture", b =>
                {
                    b.Property<int>("IdClientFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Annees")
                        .HasColumnType("int");

                    b.Property<string>("CodeDevisePrincipale")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CodeDevisePrix")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EstArrierePreExistant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdFacture")
                        .HasColumnType("int");

                    b.Property<string>("Mois")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantDu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantDuDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantPaye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("MontantPayeDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("TauxVersDevisePrincipale")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("nombreBatiment")
                        .HasColumnType("int");

                    b.HasKey("IdClientFacture");

                    b.HasIndex("DateEmission")
                        .HasDatabaseName("IX_ClientFacture_DateEmission");

                    b.HasIndex("IdClient")
                        .HasDatabaseName("IX_ClientFacture_IdClient");

                    b.HasIndex("IdFacture")
                        .HasDatabaseName("IX_ClientFacture_IdFacture");

                    b.HasIndex("MontantDu")
                        .HasDatabaseName("IX_ClientFacture_MontantDu");

                    b.HasIndex("DateModification", "IdClientFacture")
                        .HasDatabaseName("IX_ClientFactures_Sync");

                    b.HasIndex("IdClient", "Mois", "Annees")
                        .HasDatabaseName("IX_ClientFacture_Client_Mois_Annees");

                    b.ToTable("ClientFactures");
                });

            modelBuilder.Entity("Kenergie.Models.ClientUsage", b =>
                {
                    b.Property<int>("IdClientUsage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeDeCourant")
                        .HasColumnType("int");

                    b.Property<int>("IdUsage")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("nombreBatiment")
                        .HasColumnType("int");

                    b.HasKey("IdClientUsage");

                    b.HasIndex("IdClient")
                        .HasDatabaseName("IX_ClientUsage_IdClient");

                    b.HasIndex("IdTypeDeCourant")
                        .HasDatabaseName("IX_ClientUsage_IdTypeDeCourant");

                    b.HasIndex("IdUsage")
                        .HasDatabaseName("IX_ClientUsage_IdUsage");

                    b.HasIndex("IdClient", "IdUsage")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientUsage_Client_Usage_Unique");

                    b.ToTable("ClientUsages");
                });

            modelBuilder.Entity("Kenergie.Models.CommunicationCampaign", b =>
                {
                    b.Property<int>("IdCampagne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("ActiverEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ActiverInApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ActiverPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ActiverSms")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CriteresCiblage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEnvoiEffectif")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstEnCours")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstProgrammee")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateurCreateur")
                        .HasColumnType("int");

                    b.Property<string>("ListeIdClients")
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreDestinataires")
                        .HasColumnType("int");

                    b.Property<int>("NombreEchecs")
                        .HasColumnType("int");

                    b.Property<int>("NombreEnvoyes")
                        .HasColumnType("int");

                    b.Property<int>("NombreSucces")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TypeCampagne")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCampagne");

                    b.HasIndex("IdSociete");

                    b.HasIndex("IdUtilisateurCreateur");

                    b.ToTable("CommunicationCampaigns");
                });

            modelBuilder.Entity("Kenergie.Models.DeviseMonetaire", b =>
                {
                    b.Property<int>("IdDeviseMonetaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeDevise")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbole")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdDeviseMonetaire");

                    b.HasIndex("IdSociete", "CodeDevise")
                        .IsUnique()
                        .HasDatabaseName("UX_DevisesMonetaires_Societe_Code");

                    b.ToTable("DevisesMonetaires", (string)null);
                });

            modelBuilder.Entity("Kenergie.Models.DiffusionStatistique", b =>
                {
                    b.Property<int>("IdDiffusionStatistique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientsEchecs")
                        .HasColumnType("int");

                    b.Property<int>("ClientsNotifies")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("DureeSecondes")
                        .HasColumnType("double");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<int>("IdFacture")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateurLanceur")
                        .HasColumnType("int");

                    b.Property<string>("StatistiquesCanaux")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalClients")
                        .HasColumnType("int");

                    b.HasKey("IdDiffusionStatistique");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdFacture");

                    b.ToTable("DiffusionStatistiques");
                });

            modelBuilder.Entity("Kenergie.Models.Facture", b =>
                {
                    b.Property<int>("IdFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnneesEmission")
                        .HasColumnType("int");

                    b.Property<string>("CodeDevisePrincipale")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CodeDevisePrix")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDiffusion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstDiffusee")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdTypeDeCourant")
                        .HasColumnType("int")
                        .HasColumnName("IdTypeDeCourant");

                    b.Property<int>("IdUsage")
                        .HasColumnType("int");

                    b.Property<int>("MoisEmission")
                        .HasColumnType("int");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_facture");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("TauxVersDevisePrincipale")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("IdFacture");

                    b.HasIndex("IdTypeDeCourant");

                    b.HasIndex("IdUsage");

                    b.HasIndex("NumeroFacture")
                        .IsUnique()
                        .HasDatabaseName("IX_Facture_NumeroFacture_Unique")
                        .HasFilter("[numero_facture] IS NOT NULL");

                    b.HasIndex("MoisEmission", "AnneesEmission", "IdUsage")
                        .HasDatabaseName("IX_Facture_Mois_Annee_Usage");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Kenergie.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CanalUtilise")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstLue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int");

                    b.Property<int?>("IdDestinataire")
                        .HasColumnType("int");

                    b.Property<int?>("IdExpediteur")
                        .HasColumnType("int");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("LienAction")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatutEnvoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TrackingId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeNotification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdAgent");

                    b.HasIndex("IdDestinataire");

                    b.HasIndex("IdExpediteur");

                    b.HasIndex("IdSociete");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Kenergie.Models.NotificationPreference", b =>
                {
                    b.Property<int>("IdNotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowInApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowSms")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<bool>("OptOutFactures")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OptOutGlobal")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdNotificationPreference");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Kenergie.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientRequestId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CodeDevisePaiement")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CodeDevisePrincipale")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstPaiementArriere")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdClientFacture")
                        .HasColumnType("int");

                    b.Property<int?>("IdFacture")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("IdUtilisateur");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MethodePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("MontantAPaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantAPayeDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantPayeDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceTransaction")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ResteAPaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ResteAPayeDevisePrincipale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TauxVersDevisePrincipale")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdPaiement");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_Paiements_Idempotent");

                    b.HasIndex("DatePaiement")
                        .HasDatabaseName("IX_Paiements_DatePaiement");

                    b.HasIndex("IdClient")
                        .HasDatabaseName("IX_Paiements_IdClient");

                    b.HasIndex("IdClientFacture");

                    b.HasIndex("IdFacture")
                        .HasDatabaseName("IX_Paiements_IdFacture");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("Kenergie.Models.PanneSignalement", b =>
                {
                    b.Property<int>("IdPanneSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("NiveauImportance")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RisquesPrincipaux")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TypePanne")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPanneSignalement");

                    b.ToTable("PanneSignalements", (string)null);
                });

            modelBuilder.Entity("Kenergie.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("IdPasswordResetToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateUtilisation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPasswordResetToken");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Kenergie.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdPermission");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Kenergie.Models.PlainteClient", b =>
                {
                    b.Property<int>("IdPlainte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentaireResolution")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("EstUrgente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdAgentAssigné")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdPanneSignalement")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateurCreateur")
                        .HasColumnType("int");

                    b.Property<string>("NiveauImportance")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Priorite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RisquesPrincipaux")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("StatutPlainte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TypePanne")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPlainte");

                    b.HasIndex("IdAgentAssigné");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdPanneSignalement");

                    b.HasIndex("IdUtilisateurCreateur");

                    b.ToTable("PlainteClients");
                });

            modelBuilder.Entity("Kenergie.Models.RefreshToken", b =>
                {
                    b.Property<int>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateRevocation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdRefreshToken");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Kenergie.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdRole");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Kenergie.Models.RolePermission", b =>
                {
                    b.Property<int>("IdRolePermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateurAttribution")
                        .HasColumnType("int");

                    b.HasKey("IdRolePermission");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdRole");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Kenergie.Models.SmsLog", b =>
                {
                    b.Property<int>("IdSmsLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CodeErreur")
                        .HasColumnType("int");

                    b.Property<double>("CoutFc")
                        .HasColumnType("double");

                    b.Property<double>("CoutUsd")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DateEchec")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Direction")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NombreSegments")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDestinataire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NumeroExpediteur")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeNotification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdSmsLog");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("Kenergie.Models.Societe", b =>
                {
                    b.Property<int>("IdSociete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseResidence")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CodeDevisePrincipale")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Devise")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContact")
                        .HasColumnType("longtext");

                    b.Property<string>("GenreResponsable")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomCompletResponsable")
                        .HasColumnType("longtext");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSociete");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("Kenergie.Models.TauxChange", b =>
                {
                    b.Property<int>("IdTauxChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeDeviseCible")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CodeDeviseSource")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEffet")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<decimal>("Taux")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("IdTauxChange");

                    b.HasIndex("IdSociete", "CodeDeviseSource", "CodeDeviseCible", "DateEffet")
                        .HasDatabaseName("IX_TauxChanges_Societe_Paired_DateEffet");

                    b.ToTable("TauxChanges", (string)null);
                });

            modelBuilder.Entity("Kenergie.Models.TypeDeCourant", b =>
                {
                    b.Property<int>("IdTypeDeCourant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdTypeDeCourant");

                    b.ToTable("TypeDeCourants");
                });

            modelBuilder.Entity("Kenergie.Models.Usage", b =>
                {
                    b.Property<int>("IdUsage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdCategorieClient")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUsage");

                    b.HasIndex("IdCategorieClient");

                    b.HasIndex("Libelle", "IdCategorieClient")
                        .HasDatabaseName("IX_Usage_Libelle_IdCategorieClient");

                    b.ToTable("Usages");
                });

            modelBuilder.Entity("Kenergie.Models.UserDevice", b =>
                {
                    b.Property<int>("IdUserDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDerniereUtilisation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEnregistrement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultDevice")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUserDevice");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("Kenergie.Models.UserPermission", b =>
                {
                    b.Property<int>("IdUserPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AttribueParIdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUserPermission");

                    b.HasIndex("AttribueParIdUtilisateur");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Kenergie.Models.UserRole", b =>
                {
                    b.Property<int>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateurAttribution")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUserRole");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("IX_UserRole_IdRole");

                    b.HasIndex("IdUtilisateur")
                        .HasDatabaseName("IX_UserRole_IdUtilisateur");

                    b.HasIndex("IdUtilisateur", "IdRole")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRole_Utilisateur_Role_Unique");

                    b.HasIndex("IdUtilisateur", "Statut")
                        .HasDatabaseName("IX_UserRole_Utilisateur_Statut");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Kenergie.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseResidence")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultUsername")
                        .HasColumnType("longtext");

                    b.Property<bool>("DoitChangerMotDePasse")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<bool>("IsConnecte")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReferenceUtilisateur")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateurs_Email_Unique");

                    b.HasIndex("IdAgent");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdSociete");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Kenergie.Models.Agent", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany("Agents")
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.ArriereeCrashed", b =>
                {
                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.ClientFacture", "ClientFactureCree")
                        .WithMany()
                        .HasForeignKey("IdClientFactureCree")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("ClientFactureCree");
                });

            modelBuilder.Entity("Kenergie.Models.Axe", b =>
                {
                    b.HasOne("Kenergie.Models.Cabine", "Cabine")
                        .WithMany()
                        .HasForeignKey("IdCabine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabine");
                });

            modelBuilder.Entity("Kenergie.Models.Cabine", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.CategorieClient", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany("CategorieClients")
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.Client", b =>
                {
                    b.HasOne("Kenergie.Models.Axe", "Axe")
                        .WithMany()
                        .HasForeignKey("IdAxe")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Axe");
                });

            modelBuilder.Entity("Kenergie.Models.ClientCrashed", b =>
                {
                    b.HasOne("Kenergie.Models.Client", "ClientCree")
                        .WithMany()
                        .HasForeignKey("IdClientCree")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCree");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.ClientFacture", b =>
                {
                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Kenergie.Models.ClientUsage", b =>
                {
                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany("ClientsUsages")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.TypeDeCourant", "TypeDeCourant")
                        .WithMany("ClientUsages")
                        .HasForeignKey("IdTypeDeCourant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kenergie.Models.Usage", "Usage")
                        .WithMany("ClientsUsages")
                        .HasForeignKey("IdUsage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TypeDeCourant");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("Kenergie.Models.CommunicationCampaign", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.Utilisateur", "UtilisateurCreateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurCreateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");

                    b.Navigation("UtilisateurCreateur");
                });

            modelBuilder.Entity("Kenergie.Models.DeviseMonetaire", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.DiffusionStatistique", b =>
                {
                    b.HasOne("Kenergie.Models.CategorieClient", "CategorieClient")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieClient");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Kenergie.Models.Facture", b =>
                {
                    b.HasOne("Kenergie.Models.TypeDeCourant", "TypeDeCourant")
                        .WithMany("Factures")
                        .HasForeignKey("IdTypeDeCourant");

                    b.HasOne("Kenergie.Models.Usage", "Usage")
                        .WithMany("Factures")
                        .HasForeignKey("IdUsage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeDeCourant");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("Kenergie.Models.Notification", b =>
                {
                    b.HasOne("Kenergie.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kenergie.Models.Utilisateur", "Destinataire")
                        .WithMany("NotificationsRecues")
                        .HasForeignKey("IdDestinataire")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kenergie.Models.Utilisateur", "Expediteur")
                        .WithMany("NotificationsEnvoyees")
                        .HasForeignKey("IdExpediteur")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany("Notifications")
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Agent");

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.NotificationPreference", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.Paiement", b =>
                {
                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.ClientFacture", "ClientFacture")
                        .WithMany()
                        .HasForeignKey("IdClientFacture");

                    b.HasOne("Kenergie.Models.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("ClientFacture");

                    b.Navigation("Facture");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.PlainteClient", b =>
                {
                    b.HasOne("Kenergie.Models.Agent", "AgentAssigné")
                        .WithMany()
                        .HasForeignKey("IdAgentAssigné")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.PanneSignalement", "PanneSignalement")
                        .WithMany()
                        .HasForeignKey("IdPanneSignalement")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kenergie.Models.Utilisateur", "UtilisateurCreateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurCreateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentAssigné");

                    b.Navigation("Client");

                    b.Navigation("PanneSignalement");

                    b.Navigation("UtilisateurCreateur");
                });

            modelBuilder.Entity("Kenergie.Models.RefreshToken", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.RolePermission", b =>
                {
                    b.HasOne("Kenergie.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kenergie.Models.SmsLog", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.TauxChange", b =>
                {
                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.Usage", b =>
                {
                    b.HasOne("Kenergie.Models.CategorieClient", "CategorieClient")
                        .WithMany("Usages")
                        .HasForeignKey("IdCategorieClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategorieClient");
                });

            modelBuilder.Entity("Kenergie.Models.UserDevice", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.UserPermission", b =>
                {
                    b.HasOne("Kenergie.Models.Utilisateur", "AttribuePar")
                        .WithMany()
                        .HasForeignKey("AttribueParIdUtilisateur");

                    b.HasOne("Kenergie.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttribuePar");

                    b.Navigation("Permission");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.UserRole", b =>
                {
                    b.HasOne("Kenergie.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kenergie.Models.Utilisateur", "Utilisateur")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Kenergie.Models.Utilisateur", b =>
                {
                    b.HasOne("Kenergie.Models.Agent", "Agent")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kenergie.Models.Client", "Client")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kenergie.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kenergie.Models.Societe", "Societe")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Agent");

                    b.Navigation("Client");

                    b.Navigation("Role");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kenergie.Models.Agent", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Kenergie.Models.CategorieClient", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Kenergie.Models.Client", b =>
                {
                    b.Navigation("ClientsUsages");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Kenergie.Models.Facture", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("Kenergie.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Kenergie.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Kenergie.Models.Societe", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("CategorieClients");

                    b.Navigation("Notifications");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Kenergie.Models.TypeDeCourant", b =>
                {
                    b.Navigation("ClientUsages");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("Kenergie.Models.Usage", b =>
                {
                    b.Navigation("ClientsUsages");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("Kenergie.Models.Utilisateur", b =>
                {
                    b.Navigation("NotificationsEnvoyees");

                    b.Navigation("NotificationsRecues");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
